# Generated by Django 2.2 on 2019-06-10 09:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190606_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Enter the name of your pharmacy', max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Number must be in format: +237654686473', max_length=128, region=None, verbose_name='phone number'),
        ),
    ]
