# Generated by Django 2.2 on 2019-06-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190610_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(help_text='Enter the name of your pharmacy', max_length=100),
        ),
    ]
