# Generated by Django 2.2 on 2019-06-04 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='category of drug', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of drug', max_length=100)),
                ('des', models.TextField(help_text='drug description', max_length=200, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, help_text='please upload drug image here', null=True, upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('batch_no', models.IntegerField(verbose_name='Batch Number')),
                ('active', models.BooleanField(default=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='registration date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('added_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.Category')),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.City')),
                ('pharmacy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Pharmacy')),
            ],
            options={
                'verbose_name_plural': 'Drugs',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='OrderDrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.Drugs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ordered Drugs',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('drugs', models.ManyToManyField(to='drug.OrderDrugs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpiredDrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Drugs')),
            ],
            options={
                'verbose_name_plural': 'Expired Drugs',
            },
        ),
    ]
