# Generated by Django 2.2 on 2019-06-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_auto_20190604_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='brand_name',
            field=models.CharField(help_text='name of drug', max_length=100),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='generic_name',
            field=models.CharField(help_text='name of drug', max_length=100),
        ),
    ]
