# Generated by Django 2.2 on 2019-06-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0004_auto_20190604_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='generic_name',
            field=models.CharField(blank=True, help_text='scientific name', max_length=100, null=True, verbose_name='Generic name'),
        ),
    ]
