# Generated by Django 2.2 on 2019-06-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0005_auto_20190604_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='image',
            field=models.ImageField(blank=True, default='images/default_drug.png', help_text='please upload drug image here', null=True, upload_to='images/'),
        ),
    ]
