# Generated by Django 2.2 on 2019-06-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0008_auto_20190605_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='batch_no',
            field=models.IntegerField(help_text='Input batch number of the drug', verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.Category', verbose_name='Select Category'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='expiry_date',
            field=models.DateField(help_text='Date format: yyyy/mm/dd'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='image',
            field=models.ImageField(blank=True, default='images/default_drug.png', help_text='please upload drug image here (optional)', null=True, upload_to='images/'),
        ),
    ]
