# Generated by Django 2.2 on 2019-06-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0009_auto_20190609_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='expiry_date',
            field=models.DateField(help_text='Date format: yyyy / mm / dd'),
        ),
    ]
