# Generated by Django 2.2 on 2019-06-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0011_auto_20190609_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount price is optional', max_digits=20, null=True),
        ),
    ]
